### PR TITLE
Add support for AlphaRatio

### PR DESCRIPTION
**Pull request by AN1MATEK**
Added the PR as suggested. This is WIP and surely won't work as it is. Solves https://github.com/Audionut/Upload-Assistant/issues/7.

Thanks a lot for the development efforts.

### CODE REVIEW

**Comment by Audionut** [comment]
Nice work. I assume you've tested.

Can you please either lint the code, or check your repository settings to allow me to push updates to your pr.

**Comment by AN1MATEK** [comment]
It does not work. I have no idea how to code, I was just doing what you told me, sorry.

**Comment by Audionut** [comment]
No, I don't have access, because you forked from L4G repo and not mine. You would need to create a new fork from mine, then copy over your modified files to the new fork and create a new PR.

If you want to join discord it would be much easier to get together and troubleshoot, otherwise it's probably best to leave it for someone with site access and the ability to troubleshoot.

**Comment by swannie-eire** [comment]
It's the holiday season ATM but I'll have a look at this in the next week or so.

There is a few things the uploadarr repo is missing for AR

**Pull request closed without merging**
